### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by sponge611**
This change is [Reviewable](https://reviewable.io/reviews/reviewable/demo/3)

### CODE REVIEW

**Review by sponge611 — COMMENTED** [review]
> dd files via upload

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/reviewable/demo/3#-:-Lg8ND7vDM3HRZmXf5Pk:b-fbbxl7)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by sponge611 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/reviewable/demo/3)* status: all files reviewed, 4 unresolved discussions

___
*[ah_bootstrap.py, line 436 at r2](https://reviewable.io/reviews/reviewable/demo/3#-Lg8QLIk1hMw85rI4aHH:-Lg8QLIk1hMw85rI4aHI:b-lbut5x) ([raw file](https://github.com/reviewable/demo/blob/64024f4434f207deb0233cb0221f2b568c01a8c4/ah_bootstrap.py#L436)):*
> ```Python
> 
>     """
>     Why you do this here?
> ```

What do you mean?
___
*[ah_bootstrap.py, line 517 at r2](https://reviewable.io/reviews/reviewable/demo/3#-Lg8QEct4wJcY0P0_cSh:-Lg8QEcu33rnoX4DOZyT:b2s2ria) ([raw file](https://github.com/reviewable/demo/blob/64024f4434f207deb0233cb0221f2b568c01a8c4/ah_bootstrap.py#L517)):*
> ```Python
> 
>             gitmodules_fileobj.write(line)
>     """What's the meaning of this module"""
> ```

What is this?
___
*[ah_bootstrap.py, line 519 at r2](https://reviewable.io/reviews/reviewable/demo/3#-Lg8QIOACcN8N2VS2NAv:-Lg8QIOACcN8N2VS2NAw:bmg28gq) ([raw file](https://github.com/reviewable/demo/blob/64024f4434f207deb0233cb0221f2b568c01a8c4/ah_bootstrap.py#L519)):*
> ```Python
>     """What's the meaning of this module"""
>     gitmodules_fileobj.seek(0)
> ```

How about this 
___
*[ah_bootstrap.py, line 571 at r2](https://reviewable.io/reviews/reviewable/demo/3#-Lg8PynoCMPRlPMD-RT9:-Lg8PynoCMPRlPMD-RTA:b-i390c0) ([raw file](https://github.com/reviewable/demo/blob/64024f4434f207deb0233cb0221f2b568c01a8c4/ah_bootstrap.py#L571)):*
> ```Python
>                                                     _err_help_msg))
>         return
>     """How it can be done"""
> ```

why do you add this here

**Review by sponge611 — COMMENTED** [review]
12366+59

> *[Reviewable](https://reviewable.io/reviews/reviewable/demo/3#-:-Lg8aP5d5PpN4Lw__BHj:b5fv142)* status: all files reviewed, 2 unresolved discussions

**Review by sponge611 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/reviewable/demo/3)* status: all files reviewed, 3 unresolved discussions

___
*[ah_bootstrap.py, line 435 at r1](https://reviewable.io/reviews/reviewable/demo/3#-Lg8bhIC856QJQUILgbN:-Lg8bhIC856QJQUILgbO:b-4po64z) ([raw file](https://github.com/reviewable/demo/blob/fbe9d3e39daae4536c405fefef9a00ff030bf626/ah_bootstrap.py#L435)):*
> ```Python
>                 '`git submodule status` command:\n{0}'.format(str(e)))
> ```

IS THERE ANY HELP?

**Review by sponge611 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/reviewable/demo/3)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @sponge611)

___
*[ah_bootstrap.py, line 520 at r2](https://reviewable.io/reviews/reviewable/demo/3#-Lg8cukY7jZYfo0pR2Gf:-Lg8cukY7jZYfo0pR2Gg:b2ngxzh) ([raw file](https://github.com/reviewable/demo/blob/64024f4434f207deb0233cb0221f2b568c01a8c4/ah_bootstrap.py#L520)):*
> ```Python
>     gitmodules_fileobj.seek(0)
> 
>     cfg = RawConfigParser()
> ```

123

**Review by sponge611 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/reviewable/demo/3)* status: all files reviewed, 4 unresolved discussions

___
*[ah_bootstrap.py, line 436 at r2](https://reviewable.io/reviews/reviewable/demo/3#-Lg8QLIk1hMw85rI4aHH:-Lg8ekdu72dYzxvWtQ9s:bb6h7kt) ([raw file](https://github.com/reviewable/demo/blob/64024f4434f207deb0233cb0221f2b568c01a8c4/ah_bootstrap.py#L436)):*
<details><summary><i>Previously, sponge611 wrote…</i></summary><blockquote>

What do you mean?
</blockquote></details>

123

**Review by sponge611 — COMMENTED** [review]
:lgtm:123

> *[Reviewable](https://reviewable.io/reviews/reviewable/demo/3#-:-Lg8f0NTEyknK9iuroLP:bks4y4h)* status: all files reviewed, 4 unresolved discussions

**Review by sponge611 — COMMENTED** [review]
:lgtm:nice

> *[Reviewable](https://reviewable.io/reviews/reviewable/demo/3#-:-Lg8fAT97nxRSD1E6Eub:bcdz4t8)* status: all files reviewed, 4 unresolved discussions

**Review by sponge611 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/reviewable/demo/3)* status: all files reviewed, 3 unresolved discussions

___
*[ah_bootstrap.py, line 436 at r2](https://reviewable.io/reviews/reviewable/demo/3#-Lg8QLIk1hMw85rI4aHH:-Lg8fTVY3oFdlxyVg8xz:bihg05m) ([raw file](https://github.com/reviewable/demo/blob/64024f4434f207deb0233cb0221f2b568c01a8c4/ah_bootstrap.py#L436)):*
<details><summary><i>Previously, sponge611 wrote…</i></summary><blockquote>

123
</blockquote></details>

this is for software engineering

**Review by Elpasto28 — APPROVED** [review]

**Review by Elpasto28 — APPROVED** [review]

**Review by Elpasto28 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/reviewable/demo/3)* status: all files reviewed, 3 unresolved discussions (waiting on @sponge611)

**Review by Elpasto28 — APPROVED** [review]

**Comment by Elpasto28** [comment]
#3

**Pull request closed without merging**
